### ISSUE TITLE
put in slurm/htc annotation pre-exec args

### ISSUE THREAD

**Issue by dciangot** [interlink-hq/interLink#100]
# Short Description of the issue

Look at pod annotations to understand commands to be executed before the singularity run

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by Surax98** [comment]
Implemented in Slurm Sidecar; up to @ttedeschi for HTC Sidecar
