### ISSUE TITLE
Integration test pt 2

### ISSUE THREAD

**Issue by Surax98** [interlink-hq/interLink#188]
# Short Description of the issue

#154 must be integrated as github action, since it's just a bash script, at the moment

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by dciangot** [comment]
a first version will be attempted with dagger modules on `ci` folder.

- [x] create a kubernetes cluster on demand
- [x] create an container registry on demand, to avoid contacting outer services
- [x] deploy vk and services there
- [x] apply test yaml and check the outcomes
