### ISSUE TITLE
VK recreates pods

### ISSUE THREAD

**Issue by Surax98** [interlink-hq/interLink#195]
# Short Description of the issue

If VK goes down and there are running pods, new Pods will be submitted when the VK will be brought up, having duplicated pods

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by dciangot** [comment]
Introduce the GetAllPods request (or re-use get pod with dedicated parameters e.g. all=True) to be called at the beginning of the vk start. 

Scope: disaster recovery
