### ISSUE TITLE
Interlink recreates cache

### ISSUE THREAD

**Issue by Surax98** [interlink-hq/interLink#198]
# Short Description of the issue

If InterLink goes down, it must recreate its cache by querying below sidecar

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by dciangot** [comment]
out dated in favor of https://github.com/interTwin-eu/interLink/issues/206 , right @Surax98 ?

**Comment by Surax98** [comment]
Yes
