### ISSUE TITLE
Slight API rework

### ISSUE THREAD

**Issue by Surax98** [interlink-hq/interLink#206]
# Short Description of the issue

Due to what has been discussed on #201, it seems logic a Job ID must be returned from the sidecar and associated to a pod on the VK side. It appears necessary to:
- return a struct from the create call
- remove the possibility to submit multiple pods within one call

@Bianco95 and @ttedeschi please take a look on your sidecars

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by dciangot** [comment]
done in 0.3.0
