### ISSUE TITLE
Disabling jaeger tracing 

### ISSUE THREAD

**Issue by landerlini** [interlink-hq/interLink#231]
Jaeger tracing uses a large amount of resources, in particular memory. 

In setups with multiple virtual nodes, the sum resources of the all-in-one-linux containers may increase to several GB. 

It would be important to:
 * document how to switch off jaeger (simply removing the container breaks the interLink inttw-vk container)
 * (if possible) document how to modify the target of the gRPC of jaeger to use a single instance for multiple nodes.

**Comment by dciangot** [comment]
done in 0.3.0
