### ISSUE TITLE
Virtual node should mark pods as Failed upon failed authentication

### ISSUE THREAD

**Issue by landerlini** [interlink-hq/interLink#232]
In a setup with oauth2-proxy providing the authentication of the client application accessing the interlink core server, it may happen that the authentication token is not refreshed properly and requires generating a new refresh token.

When this happens, the pods are submitted to the virtual node but they never reach the core server because they get stopped by the authentication step. Those pods should be marked as Pending (or at least Failed)  rather than "Waiting for InitContainers" as they are marked today.

You may want to consider checking the authentication (through a pinglink for example) just before submitting the pod and leave the pod pending until the authentication is granted.

**Comment by dciangot** [comment]
This one looks like related to the wrong node status management, for which we should try after the related PR is merged. It will likely be included in the CI one here https://github.com/interTwin-eu/interLink/pull/227

**Comment by dciangot** [comment]
@landerlini let me know if this is fixed now in 0.3.0
