### ISSUE TITLE
Refresh token not reused

### ISSUE THREAD

**Issue by antoinetran** [interlink-hq/interLink#259]
Refresh token should be renewed and reused to get new tokens. Instead, currently, it uses the first token provided by ENV, which will then expire in 15min.

Correction: quite simple, put the read code of the token inside the while loop: https://github.com/interTwin-eu/interLink/blob/main/docker/scripts/refresh.py#L30

If I have the time, I might do a pull request.

Symptoms:
```
response {'error': 'bad_refresh_token', 'error_description': 'The refresh token passed is incorrect or expired.', 'error_uri': 'https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code'}
```

Fix:
```
    try:
        with open(output_file+"-refresh", "r") as text_file:
            rt = text_file.readline()
        if rt != "": 
            iam_refresh_token = rt
    except:
        logging.info("No cache for refresh token, starting from ENV value")

    print(iam_refresh_token)
    token = None

    while True:
```
to

```
    while True:
        try:
            with open(output_file+"-refresh", "r") as text_file:
                rt = text_file.readline()
            if rt != "": 
                iam_refresh_token = rt
        except:
            logging.info("No cache for refresh token, starting from ENV value")
    
        print(iam_refresh_token)
        token = None

```

**Comment by antoinetran** [comment]
Also debugging was difficult, setting to logging to DEBUG would be great :) And I don't know why but all print are hidden

**Comment by dciangot** [comment]
thanks @antoinetran for reporting this!
I'd like to put it into the upcoming patch release for 0.3.0 and I'd also like you to do a PR, but if you don't have time for it just let me know and I will do.

**Comment by antoinetran** [comment]
@dciangot Hi, during my test, I also saw a missing rbac
```
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
```
Which fixed the error `Unable to retrieve all namespaces available in the cluster`
Should I create a another issue?

**Comment by dciangot** [comment]
No, thanks, no need. That is already put in a pr for the patch mentioned above
