### ISSUE TITLE
Helm chart to deploy VK should not deploy ssh services by default

### ISSUE THREAD

**Issue by Bianco95** [interlink-hq/interLink#297]
I followed the guide https://intertwin-eu.github.io/interLink/docs/Cookbook and then I used the helm chart to deploy the VK like described in the tutorial.
```
helm upgrade --install --create-namespace -n interlink my-virtual-node oci://ghcr.io/intertwin-eu/interlink-helm-chart/interlink --values ./values.yaml
```
But it gives the following error:
```
Error: UPGRADE FAILED: failed to create resource: Service "ssh-bastion-my-virtual-node" is invalid: spec.ports[0].nodePort: Invalid value: 31022: provided port is already allocated
```
So it seems that it want to create a ssh service but I don't request it.

**Comment by dciangot** [comment]
This should be solved now. Closing, please reopen if otherwise
