### ISSUE TITLE
Include repository tag/commit version in documentation

### ISSUE THREAD

**Issue by chbrandt** [interlink-hq/interLink#314]
# Short Description of the issue

I'm trying to fix an error in the documentation (swapped figures in Cookbook tabs "Edge"<->"In-cluster") but I'm having a hard time... I can't see a match between the rendered page and the source code, and I don't if it's my ignorance towards `mdx` or whether I'm dealing with two different versions.

By all means, though, rendered documentation with information about the commit/tag it was generated from is a solid improvements for (new) docs contributors.

# Summary of proposed changes

At the bottom of documentation pages, `https://intertwin-eu.github.io/interLink/docs/*`, put a note "Documentation rendered from version ${commit}".

**Comment by dciangot** [comment]
I think that at the moment doc is rendered always from the latest commit in main. Can you explain further your solution @chbrandt ?

**Comment by chbrandt** [comment]
No, I actually cannot since I have no experience with Docusaurus. It's all good, though, the issue was a suggestion around my ignorance. Eventually I could find the information and why I was not seeing it (partially rendered page on github).
