### ISSUE TITLE
install script duplicate/appends multiple interlink configuration

### ISSUE THREAD

**Issue by dciangot** [interlink-hq/interLink#319]
# Short Description of the issue

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by waveywaves** [comment]
Can confirm, have seen this as well. The ~/.interlink/config/InterLinkConfig.yaml has at least 4 duplicate configuration entries.

**Comment by dciangot** [comment]
should be fixed in 0.3.4
