### ISSUE TITLE
Errors inside kubeconfig sa setup are ignored

### ISSUE THREAD

**Issue by dciangot** [interlink-hq/interLink#62]
https://github.com/interTwin-eu/interLink/blob/f53c66e730f0c70d21edcc8aa4f7d690b69a8185/pkg/common/func.go#L148C5-L148C5

@Surax98 high prio

**Comment by Surax98** [comment]
I'm not getting what you mean. Errors are detected and returned from the function. In the VK package the error is then checked:
https://github.com/interTwin-eu/interLink/blob/f53c66e730f0c70d21edcc8aa4f7d690b69a8185/pkg/virtualkubelet/virtualkubelet.go#L157

**Comment by Surax98** [comment]
to be closed @dciangot
