### ISSUE TITLE
Add log info on which file is taken and where at configuration time

### ISSUE THREAD

**Issue by dciangot** [interlink-hq/interLink#64]
https://github.com/interTwin-eu/interLink/blob/f53c66e730f0c70d21edcc8aa4f7d690b69a8185/pkg/virtualkubelet/virtualkubelet.go#L163C31-L163C45

above an example, if the configuration fails there, we have no clue from the logs of what is the problem and where to look

@Surax98 high prio

**Comment by Surax98** [comment]
to be closed @dciangot
