### ISSUE TITLE
Unable to retrieve job status: Usage: grep

### ISSUE THREAD

**Issue by dciangot** [interlink-hq/interLink#95]
# Short Description of the issue

## Environment

- Operating System:
- Other related components versions:

## Logs, stacktrace, or other symptoms

```shell
output
```

# Summary of proposed changes

**Comment by dciangot** [comment]
time="2023-09-19T12:08:06+02:00" level=info msg="           3881504       cpu test-pod ciangott  R 1-01:29:53      1 cn0114\n"
time="2023-09-19T12:08:06+02:00" level=error msg="Unable to retrieve job status: Usage: grep [OPTION]... PATTERNS [FILE]...\nTry 'grep --help' for more information.\n"

**Comment by Surax98** [comment]
will be checked later if it happens again
